#!/usr/bin/env bash

rm -f *~
rm -f hmm/recipe/*.pyc
rm -f *~
rm -f data/omlette/ingredients/*~
rm -f data/omlette/recipes/*~
rm -f data/pbnj/ingredients/*~
rm -f data/pbnj/recipes/*~
rm -f data/chocolate_cake/ingredients/*~
rm -f data/chocolate_cake/recipes/*~
rm -f data/biriyani/ingredients/*~
rm -f data/biriyani/recipes/*~
git add -A
git commit -m "$*"
git pull origin master
git push origin master
