#!/usr/bin/env bash

rm -f hmm/recipe/*.pyc
rm -f ingredients/*~
rm -f recipes/*~
rm -f *~
rm -f test/ingredients/*~
rm -f test/recipes/*~
rm -f test/dish_names/*~
git add -A
git commit -m "$*"
git push origin master
